### ISSUE TITLE
Document Editor Components

### ISSUE THREAD

**Issue by CallmeT-ty** [powerhouse-inc/codegen#14]
The document editor components are the granular components that will later be reused for different document models and will be implemented in the RWA reporting document model. 

The detailed user stories can be found here
https://www.notion.so/makerdao-ses/DEC-1-Document-Editor-Component-ba6ef90497844c0c85210bbb3e855fe2

The detailed design files can be found here 
https://www.figma.com/file/smPdlkqKN4briSrWwzam4U/DEC-1--Document-Editor-Component?type=design&node-id=6601-16505&mode=design&t=w3Igkc4JEBWvBfuW-0

# User Stories / Editor Components
The following user stories focus on the editor controls that will be applicable to the RWA reporting demo of feb 15th.

- [ ] DEC-1.01 Version Control Dropdown (❌ 'required' not for demo)
- [ ] DEC-1.02 Navigation Subtabs (❌ 'required' not for demo)
- [ ] DEC-1.03 Filter Dropdown (❌ 'required' not for demo)
- [ ] DEC-1.04 Data element: Tables  (🟢 required for demo) 
- [ ] DEC-1.05 Comparison views for documents (❌ 'required' not for demo)
- [ ] DEC-1.06 Color legend for doc. adjustments (❌ 'required' not for demo)
- [ ] DEC-1.07 Asset View & Edit Modal (🟢 required for demo) 
- [ ] DEC-1.08 Attachments Modal (❌ 'required' not for demo)
- [ ] DEC-1.09 Input components for transactions (🟢 required for demo)

**Comment by gpuente** [comment]
Linked tickets:

- https://github.com/powerhouse-inc/design-system/issues/147
- https://github.com/powerhouse-inc/design-system/issues/148
- https://github.com/powerhouse-inc/design-system/issues/149
- https://github.com/powerhouse-inc/design-system/issues/150
- https://github.com/powerhouse-inc/design-system/issues/151
- https://github.com/powerhouse-inc/design-system/issues/152
- https://github.com/powerhouse-inc/document-model-libs/issues/54
- https://github.com/powerhouse-inc/document-model-libs/issues/55
- https://github.com/powerhouse-inc/document-model-electron/issues/74
